(define (problem CantiBoxLeft_process)
	(:domain domain_name)
	(:objects CL3 CL3M PG1000 PG1500 PG500 b0 b1 b12 b13 b2 b3 b4 b5 b6 b7 b8 b9 c1 c2 c3 c4 g1 g2 g3)
	(:init 
		(AssemblyByClampingMethod b12)
		(AssemblyByClampingMethod b13)
		(AssemblyByClampingMethod b2)
		(AssemblyByClampingMethod b3)
		(AssemblyByClampingMethod b4)
		(AssemblyByClampingMethod b5)
		(AssemblyByClampingMethod b6)
		(AssemblyByClampingMethod b7)
		(AssemblyByClampingMethod b8)
		(AssemblyByClampingMethod b9)
		(AssemblyByGroundConnection b0)
		(AssemblyByGroundConnection b1)
		(Beam b0)
		(Beam b1)
		(Beam b12)
		(Beam b13)
		(Beam b2)
		(Beam b3)
		(Beam b4)
		(Beam b5)
		(Beam b6)
		(Beam b7)
		(Beam b8)
		(Beam b9)
		(BeamAtStorage b0)
		(BeamAtStorage b1)
		(BeamAtStorage b12)
		(BeamAtStorage b13)
		(BeamAtStorage b2)
		(BeamAtStorage b3)
		(BeamAtStorage b4)
		(BeamAtStorage b5)
		(BeamAtStorage b6)
		(BeamAtStorage b7)
		(BeamAtStorage b8)
		(BeamAtStorage b9)
		(BeamNeedsGripperType b0 PG1500)
		(BeamNeedsGripperType b1 PG1500)
		(BeamNeedsGripperType b12 PG1500)
		(BeamNeedsGripperType b13 PG1500)
		(BeamNeedsGripperType b2 PG1500)
		(BeamNeedsGripperType b3 PG1500)
		(BeamNeedsGripperType b4 PG1500)
		(BeamNeedsGripperType b5 PG1500)
		(BeamNeedsGripperType b6 PG1500)
		(BeamNeedsGripperType b7 PG1500)
		(BeamNeedsGripperType b8 PG1500)
		(BeamNeedsGripperType b9 PG1500)
		(Clamp c1)
		(Clamp c2)
		(Clamp c3)
		(Clamp c4)
		(ClampAtStorage c1)
		(ClampAtStorage c2)
		(ClampAtStorage c3)
		(ClampAtStorage c4)
		(ClampOfType c1 CL3)
		(ClampOfType c2 CL3)
		(ClampOfType c3 CL3M)
		(ClampOfType c4 CL3M)
		(Gripper g1)
		(Gripper g2)
		(Gripper g3)
		(GripperAtStorage g1)
		(GripperAtStorage g2)
		(GripperAtStorage g3)
		(GripperOfType g1 PG500)
		(GripperOfType g2 PG1000)
		(GripperOfType g3 PG1500)
		(Joint b0 b2)
		(Joint b0 b5)
		(Joint b1 b3)
		(Joint b1 b7)
		(Joint b2 b4)
		(Joint b2 b6)
		(Joint b2 b9)
		(Joint b3 b4)
		(Joint b3 b8)
		(Joint b3 b9)
		(Joint b5 b12)
		(Joint b5 b13)
		(Joint b5 b6)
		(Joint b7 b12)
		(Joint b7 b13)
		(Joint b7 b8)
		(JointNeedsClampType b0 b2 CL3M)
		(JointNeedsClampType b0 b5 CL3M)
		(JointNeedsClampType b1 b3 CL3)
		(JointNeedsClampType b1 b7 CL3)
		(JointNeedsClampType b2 b4 CL3M)
		(JointNeedsClampType b2 b6 CL3M)
		(JointNeedsClampType b2 b9 CL3)
		(JointNeedsClampType b3 b4 CL3)
		(JointNeedsClampType b3 b8 CL3)
		(JointNeedsClampType b3 b9 CL3M)
		(JointNeedsClampType b5 b12 CL3)
		(JointNeedsClampType b5 b13 CL3)
		(JointNeedsClampType b5 b6 CL3)
		(JointNeedsClampType b7 b12 CL3M)
		(JointNeedsClampType b7 b13 CL3)
		(JointNeedsClampType b7 b8 CL3M))
	(:goal (and (BeamAtAssembled b1) (BeamAtAssembled b0) (BeamAtAssembled b2) (BeamAtAssembled b3) (BeamAtAssembled b4) (BeamAtAssembled b9) (BeamAtAssembled b5) (BeamAtAssembled b6) (BeamAtAssembled b7) (BeamAtAssembled b12) (BeamAtAssembled b13) (BeamAtAssembled b8) (GripperAtStorage g1) (GripperAtStorage g2) (GripperAtStorage g3) (ClampAtStorage c1) (ClampAtStorage c2) (ClampAtStorage c3) (ClampAtStorage c4))))
