(define (problem CantiBoxLeft_process)
	(:domain domain_name)
	(:objects PG1000 PG1500 PG500 b0 b1 b2 b3 g1 g2 g3)
	(:init 
		(Beam b0)
		(Beam b1)
		(Beam b2)
		(Beam b3)
		(BeamAtStorage b0)
		(BeamAtStorage b1)
		(BeamAtStorage b2)
		(BeamAtStorage b3)
		(BeamNeedsGripperType b0 PG1500)
		(BeamNeedsGripperType b1 PG1500)
		(BeamNeedsGripperType b2 PG1500)
		(BeamNeedsGripperType b3 PG1500)
		(GripperAtStorage g1)
		(GripperAtStorage g2)
		(GripperAtStorage g3)
		(GripperOfType g1 PG500)
		(GripperOfType g2 PG1000)
		(GripperOfType g3 PG1500)
		(Joint b0 b2)
		(Joint b1 b3))
	(:goal (and (BeamAtAssembled b1) (BeamAtAssembled b0) (BeamAtAssembled b2) (BeamAtAssembled b3) (GripperAtStorage g1) (GripperAtStorage g2) (GripperAtStorage g3))))
