(define (problem CantiBoxMid_process)
	(:domain beam_assembly)
	(:objects b0 b1 b10 b11 b12 b13 b14 b15 b16 b17 b18 b19 b2 b3 b4 b5 b6 b7 b8 b9)
	(:init 
		(BeamAtStorage b0)
		(BeamAtStorage b1)
		(BeamAtStorage b10)
		(BeamAtStorage b11)
		(BeamAtStorage b12)
		(BeamAtStorage b13)
		(BeamAtStorage b14)
		(BeamAtStorage b15)
		(BeamAtStorage b16)
		(BeamAtStorage b17)
		(BeamAtStorage b18)
		(BeamAtStorage b19)
		(BeamAtStorage b2)
		(BeamAtStorage b3)
		(BeamAtStorage b4)
		(BeamAtStorage b5)
		(BeamAtStorage b6)
		(BeamAtStorage b7)
		(BeamAtStorage b8)
		(BeamAtStorage b9))
	(:goal (and (BeamAtAssembled b0) (BeamAtAssembled b1) (BeamAtAssembled b2) (BeamAtAssembled b3) (BeamAtAssembled b4) (BeamAtAssembled b5) (BeamAtAssembled b6) (BeamAtAssembled b7) (BeamAtAssembled b8) (BeamAtAssembled b9) (BeamAtAssembled b10) (BeamAtAssembled b11) (BeamAtAssembled b12) (BeamAtAssembled b13) (BeamAtAssembled b14) (BeamAtAssembled b15) (BeamAtAssembled b16) (BeamAtAssembled b17) (BeamAtAssembled b18) (BeamAtAssembled b19))))
